
version: 2
before:
  hooks:
    - make clean

builds:
  - main: ./main.go
    binary: go-gen
    ldflags:
      - -s -w -X github.com/limingxinleo/go-gen/cmd.version={{.Version}}
    goos:
      - darwin
      - linux
      - windows
    env:
      - CGO_ENABLED=0

archives:
  - name_template: >-
      {{- .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
    format_overrides:
      - goos: windows
        formats: [zip]